### ISSUE TITLE
CSS file issue with docs

### ISSUE THREAD

**Issue by pmackay** [spotify/ramlfications#24]
On http://ramlfications.readthedocs.org/en/latest/index.html it seems the CSS files are not loading correctly because of:

`The stylesheet https://media.readthedocs.org/css/sphinx_rtd_theme.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".`

`The stylesheet https://media.readthedocs.org/css/readthedocs-doc-embed.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".`

**Comment by econchick** [comment]
Interesting - thanks for letting me know; will look into this!

**Comment by econchick** [comment]
Hey @pmackay - do you get the same error if you use `https` instead of `http`?  

I've tried in Chrome, Firefox, and Safari, and I can't seem to get the same error messages you're getting.  I've tried both `http` and `https`.  With just `http`, I do get an error only in Safari that says `https://media.readthedocs.org/css/theme.css.map` is not found (totally different file), while in Mozilla I get an issue with some fonts wanting to load over https instead of http.

As well, I have no control over the domain `media.readthedocs.org`, so if it is indeed a MIME type issue, then it's something I can't control :-/

**Comment by pmackay** [comment]
Its now working fine for me too, so something else must have got fixed :)
